# Generated by Django 2.2.dev20181113232241 on 2018-11-20 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('publish_year', models.DateTimeField()),
                ('style', models.CharField(choices=[('J', 'Jazz'), ('P', 'Pop music'), ('F', 'Folk music'), ('B', 'Blue'), ('C', 'Country music'), ('M', 'Mental')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('lyrics', models.TextField()),
                ('album', models.CharField(blank=True, default='', max_length=100)),
                ('alb_re', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
    ]
